// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8sge1bC0iZwj4Fm_NfBZPZLOBUzrqLE',
    appId: '1:318081352556:web:9605219c73f59ef2d5e949',
    messagingSenderId: '318081352556',
    projectId: 'kanver-77687',
    authDomain: 'kanver-77687.firebaseapp.com',
    storageBucket: 'kanver-77687.appspot.com',
    measurementId: 'G-8K5MDZC0G7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBZaXRZcIbuCpTLtSivRN2Gvodc8QJqac',
    appId: '1:318081352556:android:c36ae3cd07e3a6f6d5e949',
    messagingSenderId: '318081352556',
    projectId: 'kanver-77687',
    storageBucket: 'kanver-77687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK3rghsdJ4e0HozzsHN-sCrRCs4ZDN6Cg',
    appId: '1:318081352556:ios:87f08e681dbd41fed5e949',
    messagingSenderId: '318081352556',
    projectId: 'kanver-77687',
    storageBucket: 'kanver-77687.appspot.com',
    iosBundleId: 'com.example.kanverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK3rghsdJ4e0HozzsHN-sCrRCs4ZDN6Cg',
    appId: '1:318081352556:ios:88d92718a72ac8a1d5e949',
    messagingSenderId: '318081352556',
    projectId: 'kanver-77687',
    storageBucket: 'kanver-77687.appspot.com',
    iosBundleId: 'com.example.kanverApp.RunnerTests',
  );
}
